<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerI9hVZ0m\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerI9hVZ0m/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerI9hVZ0m.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerI9hVZ0m\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerI9hVZ0m\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'I9hVZ0m',
    'container.build_id' => 'ca7e989a',
    'container.build_time' => 1523952631,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerI9hVZ0m');
